version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - sactudonet

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    networks:
      - sactudonet

networks:
  sactudonet:
    external: true