version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - registration-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: registration_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - registration-network

networks:
  registration-network:
    driver: bridge

volumes:
  db_data: